# Pipeline Referenciador - fe-processmaker-acz-screens
# Author: @ruben.jimenez@zurich.com
#
# PROPÓSITO: Análisis Sonar bajo demanda (manual trigger).
# Toda la lógica real está en devops-processmaker.

name: '$(Rev:rr)'

trigger: none

resources:
  repositories:
    - repository:                              AppDevOpsRepo
      type:                                    git
      name:                                    LA-CO-FENIX/devops-processmaker
      ref:                                     main

extends:
  template:                                    pipelines/azure/fe-processmaker-acz-screens/azure-pipelines-ci.yml@AppDevOpsRepo
