
sonar.projectKey=Lib-zurich
sonar.projectName=fs-lib-zurich

# Rutas de código y tests
sonar.sources=projects/lib-zurich/src
sonar.exclusions=**/*.spec.ts, **/environment*.ts
sonar.tests=projects/lib-zurich/src
sonar.test.inclusions=**/*.spec.ts

# Cobertura (TypeScript)
sonar.typescript.lcov.reportPaths=coverage/lib-zurich/lcov.info

# Resultado de ejecución de tests (Generic Test Data)
#sonar.testExecutionReportPaths=reports/junit/unit-test-results.xml
sonar.junit.reportPaths=reports/junit

# URL del servidor
sonar.host.url=https://sonarqube.zurich.com
# Para SonarCloud:
#sonar.host.url=https://sonarcloud.io
# sonar.organization=tu_organizacion
